const learner=["apple","beach","bread","chair","cloud","dream","earth","field","fruit","glass","green","happy","heart","house","light","money","music","night","ocean","paper","plant","quick","river","round","school","shirt","smile","sound","space","stone","table","teach","today","train","water","white","world","write","young","zebra","mouse","phone","clock","grape","sweet","laugh","story","small","great","under","every","never"];
const advanced=["abide","acute","adorn","amble","ardor","beget","blithe","brisk","cairn","chasm","civic","crave","deign","droll","edict","elate","ethos","fable","flair","forge","guile","hasty","idiom","jaunt","knack","lithe","lucid","mirth","naive","niche","ovary","pique","quell","realm","rebus","rivet","savor","stoic","tacit","tenet","tryst","ultra","vigor","waive","wryly","yearn","zesty","adage","aloof","brine","caste","deter","feign","gruel","hoist","inert","joust","knead","leery","motif"];
const tips=["Start with common vowels and consonants.","Gold letters belong in the word, but need to move.","The secret word may contain the same letter twice.","Use early guesses to test several new letters."];
let mode="learner",secret="",row=0,guess="",done=false,history=[];
const $=id=>document.getElementById(id);
function list(){return mode==="learner"?learner:[...learner,...advanced]}
function day(){return Math.floor((Date.now()-Date.UTC(2024,0,1))/86400000)}
function choose(random=false){const a=list();return random?a[Math.floor(Math.random()*a.length)]:a[(day()*17+(mode==="advanced"?11:0))%a.length]}
function board(){ $("board").innerHTML="";for(let r=0;r<6;r++){let d=document.createElement("div");d.className="row";for(let c=0;c<5;c++){let t=document.createElement("div");t.className="tile";t.dataset.r=r;t.dataset.c=c;d.appendChild(t)}$("board").appendChild(d)}}
function keyboard(){let k=$("keyboard");k.innerHTML="";["QWERTYUIOP","ASDFGHJKL"].forEach(s=>{let d=document.createElement("div");d.className="keyrow";[...s].forEach(x=>d.appendChild(key(x)));k.appendChild(d)});let d=document.createElement("div");d.className="keyrow";d.appendChild(key("ENTER",1));[..."ZXCVBNM"].forEach(x=>d.appendChild(key(x)));d.appendChild(key("⌫",1));k.appendChild(d)}
function key(x,w){let b=document.createElement("button");b.className="key"+(w?" wide":"");b.textContent=x;b.dataset.key=x;b.onclick=()=>press(x);return b}
function paint(){document.querySelectorAll(`[data-r="${row}"]`).forEach((t,i)=>{t.textContent=guess[i]||"";t.classList.toggle("filled",!!guess[i])})}
function evalGuess(g){let out=Array(5).fill("absent"),rem=secret.split("");for(let i=0;i<5;i++)if(g[i]===secret[i]){out[i]="exact";rem[i]=null}for(let i=0;i<5;i++)if(out[i]!=="exact"){let j=rem.indexOf(g[i]);if(j>-1){out[i]="present";rem[j]=null}}return out}
function press(k){if(done)return;if(k==="⌫"||k==="Backspace"){guess=guess.slice(0,-1);paint();return}if(k==="ENTER"){submit();return}if(/^[A-Z]$/i.test(k)&&guess.length<5){guess+=k.toLowerCase();paint()}}
function submit(){if(guess.length!==5){toast("Five letters, please.");return}let g=guess,e=evalGuess(g);history.push({g,e});document.querySelectorAll(`[data-r="${row}"]`).forEach((t,i)=>{t.classList.add(e[i]);let kb=document.querySelector(`[data-key="${g[i].toUpperCase()}"]`);if(kb&&!kb.classList.contains("exact"))kb.classList.add(e[i])});row++;$("tries").textContent=row;if(g===secret){done=true;setTimeout(()=>finish(true),250)}else if(row===6){done=true;setTimeout(()=>finish(false),250)}else{guess="";paint()}}
function toast(x){$("toast").textContent=x;setTimeout(()=>$("toast").textContent="",1500)}
function stats(){try{return JSON.parse(localStorage.gmWordle)||{p:0,w:0,s:0,b:0}}catch{return{p:0,w:0,s:0,b:0}}}
function showStats(){let s=stats();$("played").textContent=s.p;$("win").textContent=s.p?Math.round(s.w/s.p*100)+"%":"0%";$("streak").textContent=s.s;$("best").textContent=s.b||0}
function finish(win){let s=stats();s.p++;if(win){s.w++;s.s++;s.b=s.b?Math.min(s.b,row):row}else s.s=0;localStorage.gmWordle=JSON.stringify(s);showStats();$("result").hidden=false;$("resultTitle").textContent=win?"Monster-approved.":"The word escaped.";$("resultText").textContent=win?`You found ${secret.toUpperCase()} in ${row} tries.`:`The word was ${secret.toUpperCase()}.`}
function start(random=false){secret=choose(random);row=0;guess="";done=false;history=[];board();keyboard();$("tries").textContent=0;$("title").textContent=random?"Random challenge":"Today's word";$("result").hidden=true;$("tip").textContent=tips[Math.floor(Math.random()*tips.length)]}
function switchMode(m){mode=m;$("learner").classList.toggle("active",m==="learner");$("advanced").classList.toggle("active",m==="advanced");start()}
$("learner").onclick=()=>switchMode("learner");$("advanced").onclick=()=>switchMode("advanced");$("random").onclick=()=>start(true);$("again").onclick=()=>start(true);$("restart").onclick=()=>start(false);
$("share").onclick=()=>{let map={exact:"🟩",present:"🟨",absent:"⬜"},txt=`Grammar Monster Wordle ${row}/6\n`+history.map(x=>x.e.map(y=>map[y]).join("")).join("\n");navigator.clipboard?.writeText(txt);toast("Result copied!")};
const dlg=$("dialog");$("how").onclick=()=>dlg.showModal();$("close").onclick=()=>dlg.close();$("go").onclick=()=>dlg.close();document.addEventListener("keydown",e=>{if(e.key==="Enter")press("ENTER");else if(e.key==="Backspace")press("Backspace");else if(/^[a-z]$/i.test(e.key))press(e.key)});showStats();start();